# /**
# * Setting of containers for developing html web pages.
# *
# * @author Nick
# * @date 01/08/2024
# * @detail Please use compose to execute the yaml file
# */
version: "3.8"

services:
  redhat8_7:
    build: ./centos8_4
    container_name: centos8_4
    working_dir: /programs
    restart: unless-stopped
    volumes:
      - "./workspace:/programs"
      - "./centos8_4/build.sh:/home/build.sh"
    networks:
      - dev
    command: /bin/bash -c "cd /home && ./build.sh && tail -f /dev/null"
networks:
  dev: